### ISSUE TITLE
Implement sensible "Not Found" message

### ISSUE THREAD

**Issue by schlusslicht** [cceh/kosh#82]
Currently, when using the `ids` endpoint for some non-existent ID, the API returns an error instead of a sensible "not found" message, e.g.:

```
2019-07-04 12:49:39 [ERROR] <graphql.execution.executor> An error occurred while resolving field query.ids
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/graphql/execution/executor.py", line 450, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/usr/lib/python3.7/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/kosh-0.0.1-py3.7.egg/kosh/api/graphql.py", line 50, in resolve_ids
    return search.ids(elex, ids)
  File "/usr/lib/python3.7/site-packages/kosh-0.0.1-py3.7.egg/kosh/elastic/search.py", line 29, in ids
    }) for item in find.mget(ids)]
  File "/usr/lib/python3.7/site-packages/kosh-0.0.1-py3.7.egg/kosh/elastic/search.py", line 29, in <listcomp>
    }) for item in find.mget(ids)]
AttributeError: 'NoneType' object has no attribute 'to_dict'
```

Which results in an graphql error:
```
{
  "errors": [
    {
      "message": "RequestError(400, 'Required routing not provided for documents .')",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "ids"
      ]
    }
  ],
  "data": {
    "ids": null
  }
}
```

**Comment by schlusslicht** [comment]
Closed by c75a4c9cfc39e0377ab57a0ac9ff721aa19af00b.
